### ISSUE TITLE
Germline filter

### ISSUE THREAD

**Issue by Hecate08** [aradenbaugh/radia#5]
Hello,

We are running RADIA on 6 human samples. But after all the filter steps there were many variants, which have a high alternative allele frequency in the normal DNA. How do I know if the germline filter is applied or not?

Thanks
Hecate

**Comment by aradenbaugh** [comment]
Hi Hecate,

Are you looking at the passing somatic variants?  They should have a PASS in the filter column, and SS=2 in the FORMAT column, and the word SOMATIC in the INFO column.  The germline calls will have SS=1 and will not contain the word SOMATIC in the INFO column.  There will be many passing germline variants.

Thanks,
Amie
