### ISSUE TITLE
CRITICAL	The index file for the BAM file doesn't exist

### ISSUE THREAD

**Issue by itamuria** [aradenbaugh/radia#8]
Dear Developer, 

I am trying to use RADIA with 2 DNAs and 1 RNA in bam format but I get an error.

The used command line is:

`python $radia \
    patientId \
    chrom \
    -n $dnanormal \
    -t $dnatumor \
    -r $rnatumor \
    -f $fastafile \
    -o patientId_chr1.vcf.gz \
    -i hg38 `

and the error is the next one:

> 05/18/2019 12:14:06 AM	CRITICAL	The index file for the BAM file /home/627_tumor.printed.bam doesn't exist. Please use the 'samtools index' command to create one.

The problem is that I have the index file in .bai format. 

Why could be the error? 
Thanks, 
All the best, 
Ibon

**Comment by aradenbaugh** [comment]
Hi Ibon,

It seems like something is wrong with the bam index file.  RADIA expects it to be in the same directory as the .bam file itself.  Is your .bai file in the same directory, and is it named `/home/627_tumor.printed.bam.bai`?  If it is, then maybe try recreating the index file.

You can also try running a `samtools mpileup` command on the bam file directly to test it.  If there is a problem with the .bai file, it may give you a more detailed message.

Let me know if you're still having a problem.

Thanks,
Amie

**Comment by itamuria** [comment]
Hi Amie, 

Thanks for your reply. I created again the index files and now it works. 
Thanks, 
All the best, 
Ibon
